test_anagram (__main__.TestExercice) ... ok
test_doubles (__main__.TestExercice) ... ok
test_frequence (__main__.TestExercice) ... FAIL
test_grades (__main__.TestExercice) ... ok
test_order (__main__.TestExercice) ... FAIL

======================================================================
FAIL: test_frequence (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 83, in test_frequence
    'Erreur dans les histogrammes'
AssertionError: Lists differ: [{}, {}] != [{'B': 1, 'o': 4, 'n': 2, 'j': 2, 'u': 2, '[188 chars]: 1}]

First differing element 0:
{}
{'B': 1, 'o': 4, 'n': 2, 'j': 2, 'u': 2, 'r': 2, ',': 1, ' ': 1, 'b': 1}

- [{}, {}]
+ [{' ': 1, ',': 1, 'B': 1, 'b': 1, 'j': 2, 'n': 2, 'o': 4, 'r': 2, 'u': 2},
+  {' ': 5,
+   "'": 1,
+   '/': 1,
+   'J': 1,
+   'a': 6,
+   'b': 1,
+   'c': 3,
+   'd': 1,
+   'e': 7,
+   'f': 1,
+   'g': 2,
+   'i': 5,
+   'l': 3,
+   'm': 2,
+   'n': 4,
+   'o': 4,
+   'q': 1,
+   'r': 3,
+   't': 2,
+   'u': 2}] : Erreur dans les histogrammes

======================================================================
FAIL: test_order (__main__.TestExercice)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_exercice.py", line 25, in test_order
    'Mauvais ordre'
AssertionError: Lists differ: [[1, 9, -2, 6], ['a', '2', 'hello']] != [[-2, 1, 6, 9], ['2', 'a', 'hello']]

First differing element 0:
[1, 9, -2, 6]
[-2, 1, 6, 9]

- [[1, 9, -2, 6], ['a', '2', 'hello']]
+ [[-2, 1, 6, 9], ['2', 'a', 'hello']] : Mauvais ordre

----------------------------------------------------------------------
Ran 5 tests in 0.002s

FAILED (failures=2)
